### ISSUE TITLE
AttributeError: 'module' object has no attribute 'check_basestring'

### ISSUE THREAD

**Issue by tpowellcio** [cloudnull/turbolift#103]
Fresh install of turbolift. Getting error:
```
$ turbolift -u $USER -a $KEY --os-rax-auth $REGION upload --sync -s $FILENAME -c $CONTAINER
2015-11-02 15:09:30,575 - logger:INFO => Logger [ turbolift ] loaded
2015-11-02 15:09:30,575 - worker:INFO => Authenticating
Done.
Traceback (most recent call last):
  File "/home/<username>/miniconda/envs/turbolift/bin/turbolift", line 9, in <module>
    load_entry_point('turbolift==3.0.0', 'console_scripts', 'turbolift')()
  File "build/bdist.linux-x86_64/egg/turbolift/executable.py", line 59, in execute
  File "build/bdist.linux-x86_64/egg/turbolift/worker.py", line 115, in run_manager
  File "build/bdist.linux-x86_64/egg/turbolift/authentication/auth.py", line 24, in authenticate
  File "build/bdist.linux-x86_64/egg/turbolift/authentication/utils.py", line 42, in check_auth_plugin
AttributeError: 'module' object has no attribute 'check_basestring'
```

**Comment by cloudnull** [comment]
Is this an installation of turbolift from git or PyPi? If this was from git, what version of Python was turbolift installed within?

**Comment by tpowellcio** [comment]
This was an installation from git using ```python setup.py install```
```
$ python --version
Python 2.7.10 :: Continuum Analytics, Inc.
```
