### ISSUE TITLE
Error when downloading folder from rackspace 

### ISSUE THREAD

**Issue by gulbinas** [cloudnull/turbolift#112]
```
turbolift --version
3.0.0
```

```
2017-06-14 14:36:29,391 - logger:INFO => Logger [ turbolift ] loaded
2017-06-14 14:36:29,392 - worker:INFO => Authenticating
Processing - [ \ ] - Please wait  lon
Done.
2017-06-14 14:36:30,595 - download:INFO => Listing options...
Processing - [ - ] - Please wait  Done.
2017-06-14 14:36:32,042 - download:INFO => Indexing dowload objects...
Traceback (most recent call last):
  File "/usr/local/bin/turbolift", line 11, in <module>
    load_entry_point('turbolift==3.0.0', 'console_scripts', 'turbolift')()
  File "build/bdist.macosx-10.11-x86_64/egg/turbolift/executable.py", line 59, in execute
  File "build/bdist.macosx-10.11-x86_64/egg/turbolift/worker.py", line 130, in run_manager
  File "build/bdist.macosx-10.11-x86_64/egg/turbolift/methods/download.py", line 71, in start
  File "build/bdist.macosx-10.11-x86_64/egg/turbolift/methods/download.py", line 33, in _index_objects
AttributeError: 'NoneType' object has no attribute 'endswith'
```

commands like list and delete works fine

**Comment by gulbinas** [comment]
there was missing parameter: --directory

correct command line
```turbolift -u <user> -a <access_key> --os-rax-auth lon download --container "<container name>" --directory .```
