### ISSUE TITLE
TurboLift errors with "SecurityWarning"

### ISSUE THREAD

**Issue by mxxcon** [cloudnull/turbolift#81]
On Centos 6.6 I get the following error:
```
[root@pluto grfw4_website]# turbolift -u <user> -a <apikey> --os-rax-auth ord upload -s ./ -c <bucket>
/usr/lib/python2.6/site-packages/requests-2.5.3-py2.6.egg/requests/packages/urllib3/connection.py:251: SecurityWarning: Certificate has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SecurityWarning
Processing - [ - ] - Please Wait... All Done!
Traceback (most recent call last):
  File "/usr/bin/turbolift", line 9, in <module>
    load_entry_point('turbolift==2.1.3', 'console_scripts', 'turbolift')()
  File "/usr/lib/python2.6/site-packages/turbolift-2.1.3-py2.6.egg/turbolift/executable.py", line 42, in run_turbolift
    worker.start_work()
  File "/usr/lib/python2.6/site-packages/turbolift-2.1.3-py2.6.egg/turbolift/worker.py", line 46, in start_work
    actions(auth=auth.authenticate()).start()
  File "/usr/lib/python2.6/site-packages/turbolift-2.1.3-py2.6.egg/turbolift/methods/upload.py", line 51, in start
    f_indexed = self._index_local_files()
  File "/usr/lib/python2.6/site-packages/turbolift-2.1.3-py2.6.egg/turbolift/methods/upload.py", line 34, in _index_local_files
    file_index = methods.get_local_files()
  File "/usr/lib/python2.6/site-packages/turbolift-2.1.3-py2.6.egg/turbolift/methods/__init__.py", line 95, in get_local_files
    raise turbo.SystemProblem('Died for some reason. MESSAGE:\t%s' % exp)
turbolift.SystemProblem: Died for some reason. MESSAGE: 'utf8' codec can't decode byte 0xf3 in position 90: invalid continuation byte
```

**Comment by mxxcon** [comment]
Output of `pip freeze`
```
Babel==1.3
Jinja2==2.2.1
M2Crypto==0.20.2
PyXML==0.8.4
PyYAML==3.10
ansible==1.8.4
argparse==1.2.1
d2to1==0.2.11
distribute==0.6.10
ethtool==0.6
httplib2==0.7.7
iniparse==0.3.1
iso8601==0.1.4
keyring==3.0.5
mock==1.0.1
os-diskconfig-python-novaclient-ext==0.1.1
os-networksv2-python-novaclient-ext==0.21
paramiko==1.7.5
passlib==1.5.3
pbr==0.5.21
prettytable==0.7.2
pyOpenSSL==0.10
pyasn1==0.0.12a
pycrypto==2.0.1
pycurl==7.19.0
pygpgme==0.1
pyinotify==0.9.1
pyrax==1.5.0
python-dateutil==1.4.1
python-dmidecode==3.10.13
python-keyczar==0.71c
python-novaclient==2.15.0
python-swiftclient==1.6.0
pytz==2013d
rackspace-auth-openstack==1.0
rackspace-novaclient==1.3
rax-default-network-flags-python-novaclient-ext==0.1.3
rax-scheduled-images-python-novaclient-ext==0.2.1
requests==2.5.3
rhnlib==2.5.22
rhsm==1.12.5
simplejson==2.0.9
six==1.4.1
turbolift==2.1.3
urlgrabber==3.9.1
yum-metadata-parser==1.1.2
```

**Comment by cloudnull** [comment]
The security warning can be ignored. This is related to older SSL certs on the api servers that are not RFC 2818 compliant.

I have done everything that I can think of to try and figure out what is causing this to happen on your system. I kicked a cloud server in all regions on RAX pub cloud and HP cloud and uploaded to a basic swift install, rackspace cloud files, and hp object store. I tested with a bunch of differnent character options and tried both ext3 and ext4 file systems but alas I have not been able to track this down because I can't reproduce it. 


This was some of the output from the odd file names that I uploaded. 

``` bash
+--------+--------------------------+
| bytes  | name                     |
+--------+--------------------------+
| 1406   | .bash_history            |
| 0      | ☀                        |
| 855    | .viminfo                 |
| 100    | .cshrc                   |
| 0      | ☄                        |
| 105760 | turbolift.log            |
| 0      | file name                |
| 911    | req                      |
| 0      | ☁                        |
| 129    | .tcshrc                  |
| 176    | .bash_profile            |
| 176    | .bashrc                  |
| 0      | ☂                        |
| 0      | добро                    |
| 0      | ☃                        |
| 0      | c h   |
| 456    | .ssh/authorized_keys     |
| 0      | file name other          |
| 18     | .bash_logout             |
| 302168 | .pip/pip.log             |
+--------+--------------------------+
```

Heres my pip freeze output

``` bash
[root@cloud-server-28 testing]# pip freeze
Babel==1.3
Cheetah==2.4.1
Jinja2==2.2.1
M2Crypto==0.20.2
Markdown==2.0.1
PyXML==0.8.4
PyYAML==3.10
Pygments==1.1.1
ansible==1.8.4
argparse==1.2.1
backports.ssl-match-hostname==3.4.0.2
boto==2.34.0
chardet==2.0.1
cloud-init==0.7.5
configobj==4.6.0
coverage==3.0.1
d2to1==0.2.11
distribute==0.6.10
euca2ools==2.1.4
eventlet==0.15.2
futures==2.2.0
glusterfs-api==3.6.0.29
greenlet==0.4.2
httplib2==0.9
iniparse==0.3.1
iso8601==0.1.10
jsonpatch==1.2
jsonpointer==1.0
keyring==5.3
mock==1.0.1
msgpack-python==0.4.5
netaddr==0.7.13
netifaces==0.5
nose==0.10.4
oauth==1.0.1
ordereddict==1.1
os-diskconfig-python-novaclient-ext==0.1.2
os-networksv2-python-novaclient-ext==0.25
os-virtual-interfacesv2-python-novaclient-ext==0.19
oslo.i18n==1.4.0
oslo.serialization==1.3.0
oslo.utils==1.3.0
paramiko==1.7.5
passlib==1.5.3
pbr==0.10.8
policycoreutils-default-encoding==0.1
prettytable==0.7.2
pyOpenSSL==0.10
pyasn1==0.0.12a
pycrypto==2.0.1
pycurl==7.19.0
pygpgme==0.1
pyinotify==0.9.1
pyrax==1.5.0
python-dateutil==1.4.1
python-keyczar==0.71c
python-keystoneclient==1.2.0
python-novaclient==2.22.0
python-swiftclient==2.3.1
pytz==2014.10
pyxattr==0.5.0
rackspace-auth-openstack==1.3
rackspace-novaclient==1.4
rax-default-network-flags-python-novaclient-ext==0.3.1
rax-scheduled-images-python-novaclient-ext==0.3.1
requests==2.5.3
rsa==3.1.1
setools==1.0
simplejson==3.6.5
six==1.9.0
turbolift==2.1.3
urlgrabber==3.9.1
urllib3==1.5
yum-metadata-parser==1.1.2
```

file system 

``` bash
[root@cloud-server-28 testing]# blkid
/dev/xvda1: UUID="5f6aa129-1a6d-42e6-a6d4-a53e7d20b8e7" TYPE="ext3"
```

Kernel information 

``` bash
[root@cloud-server-28 testing]# uname -a
Linux cloud-server-28 2.6.32-504.8.1.el6.x86_64 #1 SMP Wed Jan 28 21:11:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

PM me on IRC i'd be happy to work through this some more with you to try and track it all down but im at a bit of a loss as to why this is happening on your system. Sorry its taken a bit of time to get back to you on this.

**Comment by cloudnull** [comment]
I committed this little bit "https://github.com/cloudnull/turbolift/commit/8a745e316be2413a53604a341c289983e7fcaaaf" this evening in master which i think will resolve this issues from within the indexer. However, please test the last stable tag to see if the issue is resolved in the using that release.

To test these other versions you'll need to make sure you uninstall and then reinstall. e.g. ``pip uninstall turbolift``.

``` bash
# Installing from pip
pip install turbolift==v2.3.1

# Installing from github
pip install 'git+https://github.com/cloudnull/turbolift@v2.1.3'
```

**Comment by mxxcon** [comment]
reinstalling 2.1.3 or from master fixed this problem. :+1:

**Comment by cloudnull** [comment]
Thanks @mxxcon I'm wrapping up a few loose ends and then will be releasing a new stable release soon.
