### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by robbyt** [cloudnull/turbolift#85]
I'm trying to clone a bucket with 300,000+ files in it, and I'm getting the following error after transfering about 110,000 files:

```python
TB: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/turbolift/methods/__init__.py", line 111, in operation
  File "/usr/local/lib/python2.7/dist-packages/turbolift/clouderator/actions.py", line 749, in object_syncer
  File "/usr/local/lib/python2.7/dist-packages/turbolift/utils/basic_utils.py", line 101, in create_tmp
  File "/usr/lib/python2.7/tempfile.py", line 300, in mkstemp
  File "/usr/lib/python2.7/tempfile.py", line 235, in _mkstemp_inner
OSError: [Errno 24] Too many open files: '/tmp/tmpV6SPB1'
```

I've pushed up my max file descriptors really high:
```
host:~# sysctl fs.file-max
fs.file-max = 100000000
host:~# ulimit -H
unlimited
```

I was unable to find where in the Turbolift code the tmp files are closed when they're no longer needed.

**Comment by cloudnull** [comment]
@robbyt I'd assume that you've already solved your issue in another way however with the impending release of Turbolift version 3.0.0 this should no longer be an issue as the clone capability has been totally rewritten to be faster and much more memory friendly. If your feeling adventurous please checkout the tbl3 branch and or review this WIP PR [ https://github.com/cloudnull/turbolift/pull/87 ].

**Comment by cloudnull** [comment]
Turoblift3 has become master as such this issue should be fixed.
