### ISSUE TITLE
Container with unicode file names

### ISSUE THREAD

**Issue by nmorenor** [cloudnull/turbolift#94]
Hi,

Hi I'm trying to download a container that contains files with unicode characters in the name and I'm getting these errors.

Using a command like:

turbolift -u ${user} -a ${api_key} --os-rax-auth ord download -c ${container name}

File "/usr/local/lib/python2.7/urllib.py", line 1294, in quote
    return ''.join(map(quoter, s))
KeyError: u'\u0301'
Processing - [ / ] - Number of Jobs in Queue = 0  Processing workload... Done.
Processing - [ \ ] - Number of Jobs in Queue = 0  Processing workload... Done.
Processing - [ / ] - Number of Jobs in Queue = 8  Processing workload... Process Process-241864:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Processing - [ - ] - Number of Jobs in Queue = 8  Processing workload...     self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/methods/__init__.py", line 323, in _process_func
    func(**queue.get(timeout=.5))
  File "build/bdist.linux-x86_64/egg/turbolift/methods/__init__.py", line 136, in _get
    local_object=local_object
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/utils.py", line 41, in f_retry
    return f(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/actions.py", line 618, in get_items
    container_object=container_object
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/actions.py", line 69, in _return_base_data
    _container_uri, cloud_utils.quoter(container_object)
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/utils.py", line 144, in quoter
    return urllib.quote(obj)
  File "/usr/local/lib/python2.7/urllib.py", line 1294, in quote
    return ''.join(map(quoter, s))
KeyError: u'\u0301'

Awesome client, keep up the work :)

**Comment by cloudnull** [comment]
@nmorenor Thanks for reporting this issue. It seems that this is a problem in Python 2.7 and not for python 3.4. I am working on a fix and will hopefully have that up soon.

**Comment by cloudnull** [comment]
I pushed a change to master which should fix this please let me know if there continues to be an issue of if this is resolved.

**Comment by nmorenor** [comment]
Now it is not throwing the same error however, it is printing:

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py:1294: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))

Hopefully this is just a warning, and it will do the right thing.

Thanks

**Comment by cloudnull** [comment]
yea the warning is expected however with the previous commit it should pass the original data through the function. That said let me know if its not working as expected.

**Comment by nmorenor** [comment]
Hi, 

I just get in to this, seems it is concerning this same issue, with the new code from master

Process Process-13:
Traceback (most recent call last):
  File "/home/user/.pythonbrew/pythons/Python-2.7.9/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/user/.pythonbrew/pythons/Python-2.7.9/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/methods/__init__.py", line 323, in _process_func
    func(**queue.get(timeout=.5))
  File "build/bdist.linux-x86_64/egg/turbolift/methods/__init__.py", line 136, in _get
    local_object=local_object
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/utils.py", line 41, in f_retry
    return f(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/actions.py", line 625, in get_items
    local_object=local_object
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/utils.py", line 46, in f_retry
    return f(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/actions.py", line 221, in _getter
    with open(local_object, 'wb') as f_name:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 58: ordinal not in range(128)

**Comment by nmorenor** [comment]
Seems that this is related to that python brew install of python, I just tried to compile install the python 2.7.9 on that same box, it seems to be working now

Cheers
Ignacio

**Comment by nmorenor** [comment]
Mhmm... I just hit the same issue again.

UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 58: ordinal not in range(128)
Processing - [ | ] - Number of Jobs in Queue = 0  Processing workload... Process Process-724:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/methods/__init__.py", line 323, in _process_func
    func(**queue.get(timeout=.5))
  File "build/bdist.linux-x86_64/egg/turbolift/methods/__init__.py", line 136, in _get
    local_object=local_object
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/utils.py", line 41, in f_retry
    return f(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/actions.py", line 625, in get_items
    local_object=local_object
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/utils.py", line 46, in f_retry
    return f(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/actions.py", line 221, in _getter
    with open(local_object, 'wb') as f_name:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 54: ordinal not in range(128)

**Comment by cloudnull** [comment]
do you know what versions of Python you're running? Also whats the base OS? I've not been able recreate this issue in Python 2.7.10 and 3.4.3

**Comment by nmorenor** [comment]
I'm running turbolift in a linux debian 6 (squeeze) with python 2.7.9. I had to compile it to get that version of python, I also tried to use the 3.4.3 but it did not allow me to install turbolift. 

In order to make progress I had to add something like:

with open(local_object.encode("utf-8"), 'wb') as f_name:

and do the same for all other places that reference to "local_object" in "turbolift/clouderator/actions.py" _getter function. But seems that I now need to set a smaller number of jobs because of a memory error. I guess "utf-8" is expensive

**Comment by nmorenor** [comment]
This is the error I got about memory, note that I've modified some lines at "turbolift/clouderator/actions.py" 

Processing - [ - ] - Number of Jobs in Queue = 68  Processing workload... /usr/local/lib/python2.7/urllib.py:1294: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))
Processing Process Process-68296:bs in Queue = 39  Processing workload... 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/methods/__init__.py", line 323, in _process_func
    load_entry_point('turbolift==3.0.0', 'console_scripts', 'turbolift')()
  File "build/bdist.linux-x86_64/egg/turbolift/executable.py", line 59, in execute
Process Process-68295:
  File "build/bdist.linux-x86_64/egg/turbolift/worker.py", line 130, in run_manager
  File "build/bdist.linux-x86_64/egg/turbolift/methods/download.py", line 79, in start
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/turbolift/methods/__init__.py", line 298, in _multi_processor
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "build/bdist.linux-x86_64/egg/cloudlib/indicator.py", line 64, in __exit__
  File "build/bdist.linux-x86_64/egg/cloudlib/indicator.py", line 100, in stop
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 155, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/methods/__init__.py", line 323, in _process_func
Process Process-68303:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/methods/__init__.py", line 323, in _process_func
Process Process-68305:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/methods/__init__.py", line 323, in _process_func
Process Process-68300:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/methods/__init__.py", line 323, in _process_func
Process Process-68304:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/methods/__init__.py", line 323, in _process_func
Done.
Traceback (most recent call last):
  File "/usr/local/bin/turbolift", line 9, in <module>
    load_entry_point('turbolift==3.0.0', 'console_scripts', 'turbolift')()
  File "build/bdist.linux-x86_64/egg/turbolift/executable.py", line 59, in execute
  File "build/bdist.linux-x86_64/egg/turbolift/worker.py", line 130, in run_manager
  File "build/bdist.linux-x86_64/egg/turbolift/methods/download.py", line 79, in start
  File "build/bdist.linux-x86_64/egg/turbolift/methods/__init__.py", line 289, in _multi_processor
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/local/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
Process Process-68301:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114

**Comment by nmorenor** [comment]
The memory thing was a local configuration thing, however I did had to make that change to encode on uff-8 and that just work: "open(local_object.encode("utf-8"), 'wb') as f_name:" It just worked for me.

Thanks
Ignacio
