### ISSUE TITLE
Authentication failure after long run

### ISSUE THREAD

**Issue by nmorenor** [cloudnull/turbolift#95]
Hi, 

Today I hit another thing blocking my usage of turbo lift. I have a very big container that I'm trying to download, and I do not have a very fast internet connection. Eventually at some point I hit this. I've been running a turbolift process for a little less than a day, also is not the first time I get this, it just get stuck after a long run.

Processing - [ - ] - Number of Jobs in Queue = 24095  Processing workload... 2015-07-23 16:21:33,111 - exceptions:ERROR => Authentication Failure, Status: [ 401 ] Reason: [ Unauthorized ]
Process Process-602:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/methods/__init__.py", line 323, in _process_func
    func(**queue.get(timeout=.5))
  File "build/bdist.linux-x86_64/egg/turbolift/methods/__init__.py", line 136, in _get
    local_object=local_object
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/utils.py", line 41, in f_retry
    return f(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/actions.py", line 625, in get_items
    local_object=local_object
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/utils.py", line 46, in f_retry
    return f(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/actions.py", line 210, in _getter
    local_object=local_object
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/actions.py", line 84, in _sync_check
    headers=headers
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/utils.py", line 46, in f_retry
    return f(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/actions.py", line 270, in _header_getter
    self._resp_exception(resp=resp)
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/actions.py", line 414, in _resp_exception
    self.job_args.update(auth.authenticate(self.job_args))
  File "build/bdist.linux-x86_64/egg/turbolift/authentication/auth.py", line 71, in authenticate
    auth_resp.reason
AuthenticationProblem: Authentication Failure, Status: [ 401 ] Reason: [ Unauthorized ]

Seems that somehow it has lost the credentials, or the authentication.

**Comment by cloudnull** [comment]
Its likely that your token expired before the job was finished which caused the failure. Is this being deployed from master from github? If so, you can pip uninstall/install stable turbolift which has the re-authentication logic worked out to re-authenticate on 401.

**Comment by cloudnull** [comment]
To continue the operation you can pass the --sync flag to the download operation which will skip files that have already been downloaded. I am working getting the logic worked out for re-authentication however Its not there yet for master.
