### ISSUE TITLE
Error IOError: [Errno 21] Is a directory

### ISSUE THREAD

**Issue by mihaj** [cloudnull/turbolift#98]
Hi.

I am using turbolift to clone a container on rackspace with command:

```
sudo turbolift -u <user> -a <apikey> --os-rax-auth 'ord' clone -sc 'production' -tc 'staging' -tr 'ord'
```

Some of the files are transferred to the new container, but i constantly get:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/methods/__init__.py", line 323, in _process_func
    func(**queue.get(timeout=.5))
  File "build/bdist.linux-x86_64/egg/turbolift/methods/clone.py", line 117, in _check_clone
    object_headers=resp.headers
  File "build/bdist.linux-x86_64/egg/turbolift/methods/clone.py", line 93, in _clone
    local_object=local_temp_object
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/utils.py", line 41, in f_retry
    return f(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/actions.py", line 625, in get_items
    local_object=local_object
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/utils.py", line 46, in f_retry
    return f(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/turbolift/clouderator/actions.py", line 221, in _getter
    with open(local_object, 'wb') as f_name:
IOError: [Errno 21] Is a directory: u'/tmp/turbolift_qix_3S_clone/company/logo_link/881'
```

my container has a lot of folders for static files. i am using latest version of turbolink which was installed with instructions here on github.

Can you please look into it?

Thank you.

**Comment by pizarropablo** [comment]
i have same error on "upload".
```
...
2015-08-06 10:05:57,943 - upload_items:INFO => Ensuring Container...
P
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
...
```

But i dont understand what is the real error.

**Comment by cloudnull** [comment]
This looks like a bug in turbolift 3 however right now I'm away on holiday and am not able to look into it. for now, please use turbolift 2.x as it is the current stable. If you installed from master using github then you are using turbolift 3 which is under current development. I will be back at a proper computer in the next few weeks and I'll get to have a look at this then.

**Comment by mihaj** [comment]
I've downloaded 2.1.3 version and it works now! Thank you for this great tool and keep up the good work!
